### ISSUE TITLE
Deploy the Project on Vercel

### ISSUE THREAD

**Issue by Abhijit25Mishra** [iiitkottayam/InternshipPortal#2]
- Go through the vercel documentation
- Make sure that it gets hosted as soon as the repo is updated. i.e. all CI/CD features.
- Make sure branches get deployed as well and separately from the main branch

**Comment by kt24iiitk** [comment]
Name: Karthik Hegde
Roll number: 2020bcs0017
email: karthikmohan20bcs17@iiitkottayam.ac.in
I would like to take this up
